num1 = int(input("Enter a number:"))
num2 = int(input("Enter a number:"))
print("Result:-")
print("Addition: ",num1+num2)
print("Subtraction: ",num1-num2)
print("multiplication: ",num1*num2)
print("division: ",num1/num2)
print("Modulus: ",num1%num2)
print("Floor division: ",num1//num2)
print("exponentation: ",num1**num2)
